LLAVA_CLIP_PATH = '/data2/czh/models/clip-vit-large-patch14-336/'
LLAVA_MODEL_PATH = '/data2/czh/models/llava-v1.5-13b/'
SDXL_PATH = '/data2/czh/models/RealVisXL_V4.0/'
FAITHDIFF_PATH = '/data2/czh/models/faithdiff/FaithDiff.bin'
VAE_FP16_PATH = '/data2/czh/models/flux2vae/'
BSRNet_PATH = '/data2/czh/models/bsrnet/BSRNet.pth'
